# Generated by Django 4.0.6 on 2022-08-14 14:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email')),
                ('tel', models.CharField(default='', max_length=150, unique=True, verbose_name='Tel')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Job Title')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('level', models.CharField(choices=[('1', '1 - Verified user'), ('2', '2 - Approved User'), ('0', '0 - New user'), ('3', '3 - Vip user')], default='0', max_length=1, verbose_name='User Levels')),
                ('remember_me', models.BooleanField(blank=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company_name', models.CharField(blank=True, max_length=150, verbose_name='Company Name')),
                ('shipping_attention_name', models.CharField(blank=True, max_length=150, verbose_name='Attention To (Name)')),
                ('shipping_tel', models.CharField(blank=True, max_length=150, verbose_name='Contact Number')),
                ('shipping_email', models.CharField(blank=True, max_length=150, verbose_name='Contact Email')),
                ('shipping_address', models.CharField(blank=True, max_length=150, verbose_name='Address')),
                ('shipping_city', models.CharField(blank=True, max_length=150, verbose_name='City')),
                ('shipping_region', models.CharField(blank=True, max_length=150, verbose_name='State / Province / Region')),
                ('shipping_country', models.CharField(blank=True, max_length=150, verbose_name='Country')),
                ('shipping_zip', models.CharField(blank=True, max_length=150, verbose_name='Zipcode / PIN')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Company Name')),
                ('company_tel', models.CharField(blank=True, max_length=150, verbose_name='Business Tel')),
                ('company_email', models.CharField(blank=True, max_length=150, verbose_name='Contact Email')),
                ('company_web_address', models.CharField(blank=True, max_length=150, verbose_name='Web Address')),
                ('company_address', models.CharField(blank=True, max_length=150, verbose_name='Address')),
                ('company_city', models.CharField(blank=True, max_length=150, verbose_name='City')),
                ('company_region', models.CharField(blank=True, max_length=150, verbose_name='State / Province / Region')),
                ('company_country', models.CharField(blank=True, max_length=150, verbose_name='Country')),
                ('company_zip', models.CharField(blank=True, max_length=150, verbose_name='Zipcode / PIN')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
            ],
        ),
    ]
