# Generated by Django 4.0.6 on 2022-08-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='level',
            field=models.CharField(choices=[('3', '3 - Vip user'), ('0', '0 - New user'), ('1', '1 - Verified user'), ('2', '2 - Approved User')], default='0', max_length=1, verbose_name='User Levels'),
        ),
    ]
