# Generated by Django 4.0.6 on 2022-08-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customusers_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='level',
            field=models.CharField(choices=[('3', '3 - Vip user'), ('2', '2 - Approved User'), ('1', '1 - Verified user'), ('0', '0 - New user')], default='0', max_length=1, verbose_name='User Levels'),
        ),
    ]
