# Generated by Django 4.0.6 on 2022-08-23 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customusers_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Manager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customusers',
            name='level',
            field=models.CharField(choices=[('1', '1 - Verified user'), ('3', '3 - Vip user'), ('0', '0 - New user'), ('2', '2 - Approved User')], default='0', max_length=1, verbose_name='User Levels'),
        ),
    ]
