# Generated by Django 4.0.6 on 2022-08-23 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customusers_manager_alter_customusers_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='level',
            field=models.CharField(choices=[('3', '3 - Vip user'), ('2', '2 - Approved User'), ('1', '1 - Verified user'), ('0', '0 - New user')], default='0', max_length=1, verbose_name='User Levels'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='manager',
            field=models.ForeignKey(default=1, limit_choices_to={'is_staff': '1'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Manager'),
        ),
    ]
