# Generated by Django 4.0.6 on 2022-08-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customusers_level_alter_customusers_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetails',
            options={'ordering': ['pk'], 'verbose_name': 'Company Details', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['pk'], 'verbose_name': 'Shipping Address', 'verbose_name_plural': 'Shipping Address'},
        ),
        migrations.AlterField(
            model_name='customusers',
            name='level',
            field=models.IntegerField(choices=[(0, '0 - New user'), (1, '1 - Verified user'), (2, '2 - Approved User'), (3, '3 - Vip user')], default=0, verbose_name='User Level'),
        ),
    ]
