# Generated by Django 4.0.6 on 2022-09-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_companydetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='user_type',
            field=models.CharField(choices=[(0, '0 - Admin'), (1, '1 - Client'), (2, '2 - Vendor')], default=1, max_length=1, verbose_name='User Type'),
        ),
    ]
