# Generated by Django 4.0.6 on 2022-09-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customusers_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=150, unique=True, verbose_name='Tel'),
        ),
    ]
