# Generated by Django 4.0.6 on 2022-09-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customusers_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='user_type',
            field=models.IntegerField(choices=[(0, '0 - Admin'), (1, '1 - Client'), (2, '2 - Vendor')], default=1, verbose_name='User Type'),
        ),
    ]
