# Generated by Django 4.0.6 on 2022-09-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customusers_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='tel',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tel'),
        ),
    ]
