# Generated by Django 4.0.6 on 2022-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customusers_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='tel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tel'),
        ),
    ]
