# Generated by Django 4.0.6 on 2022-10-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_customusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
