# Generated by Django 4.0.6 on 2022-08-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_delete_best_selling_alter_diamond_model_cert_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Filter Name')),
                ('max', models.FloatField(max_length=255, verbose_name='Max Value')),
                ('min', models.FloatField(max_length=255, verbose_name='Min Value')),
            ],
            options={
                'verbose_name': 'Max/Min',
                'verbose_name_plural': 'Max/Min',
                'ordering': ['name'],
            },
        ),
    ]
