# Generated by Django 4.0.6 on 2022-08-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_maxmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maxmin',
            options={'ordering': ['name'], 'verbose_name': 'Max / Min Range Values', 'verbose_name_plural': 'Max / Min Range Values'},
        ),
    ]
