# Generated by Django 4.0.6 on 2022-09-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_remove_diamond_model_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamond_model',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
    ]
