# Generated by Django 4.0.6 on 2022-09-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0008_alter_diamond_model_rap_1ct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_model',
            name='depth_procent',
            field=models.IntegerField(blank=True, verbose_name='Depth %'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='rap_1ct',
            field=models.IntegerField(blank=True, verbose_name='Rap_1ct'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='sale_price',
            field=models.IntegerField(blank=True, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='table_procent',
            field=models.IntegerField(blank=True, verbose_name='Table %'),
        ),
    ]
