# Generated by Django 4.0.6 on 2022-09-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0009_alter_diamond_model_depth_procent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_model',
            name='depth_procent',
            field=models.FloatField(blank=True, verbose_name='Depth %'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='table_procent',
            field=models.FloatField(blank=True, verbose_name='Table %'),
        ),
    ]
