# Generated by Django 4.0.6 on 2022-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0010_alter_diamond_model_depth_procent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxmin',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Filter Name'),
        ),
    ]
