# Generated by Django 4.0.6 on 2022-09-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0011_alter_maxmin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_model',
            name='depth',
            field=models.FloatField(verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='disc',
            field=models.FloatField(verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='length',
            field=models.FloatField(verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='lw',
            field=models.FloatField(verbose_name='L/W'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='width',
            field=models.FloatField(verbose_name='Width'),
        ),
    ]
