# Generated by Django 4.0.6 on 2022-09-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0012_alter_diamond_model_depth_alter_diamond_model_disc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_model',
            name='weight',
            field=models.FloatField(max_length=255, verbose_name='Weight'),
        ),
    ]
