# Generated by Django 4.0.6 on 2022-09-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0013_alter_diamond_model_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamond_model',
            name='rap_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rap Price'),
            preserve_default=False,
        ),
    ]
