# Generated by Django 4.0.6 on 2022-09-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0014_diamond_model_rap_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_model',
            name='disc',
            field=models.FloatField(blank=True, verbose_name='Discount'),
        ),
    ]
