# Generated by Django 4.0.6 on 2022-09-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0015_alter_diamond_model_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_model',
            name='culet',
            field=models.CharField(blank=True, max_length=255, verbose_name='Culet'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='cut',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cut'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='depth',
            field=models.FloatField(blank=True, verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='fluor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fluour'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='girdle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Gridle'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='lab',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='length',
            field=models.FloatField(blank=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='measurements',
            field=models.CharField(blank=True, max_length=255, verbose_name='Measurements'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='photo',
            field=models.URLField(blank=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='polish',
            field=models.CharField(blank=True, max_length=255, verbose_name='Polish'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='symmetry',
            field=models.CharField(blank=True, max_length=255, verbose_name='Symmetry'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='video',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='weight',
            field=models.FloatField(blank=True, max_length=255, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='diamond_model',
            name='width',
            field=models.FloatField(blank=True, verbose_name='Width'),
        ),
    ]
