# Generated by Django 4.0.6 on 2022-09-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('vendor_name', models.CharField(max_length=255, verbose_name='Vendor Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
