# Generated by Django 4.0.6 on 2022-09-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorusers',
            old_name='vendor_name',
            new_name='username',
        ),
    ]
