# Generated by Django 4.0.6 on 2022-09-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendorusers_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Diamond_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('0', 'Round'), ('1', 'Marquise'), ('2', 'Asscher'), ('3', 'Cushion'), ('4', 'Emerald'), ('5', 'Heart'), ('6', 'Oval'), ('7', 'Pear'), ('8', 'Princess'), ('9', 'Radiant'), ('10', 'Other')], db_index=True, max_length=150, verbose_name='Shape Name')),
                ('color', models.CharField(blank=True, choices=[('0', 'M'), ('1', 'L'), ('2', 'K'), ('3', 'J'), ('4', 'I'), ('5', 'H'), ('6', 'G'), ('7', 'F'), ('8', 'E'), ('9', 'D')], db_index=True, max_length=150, verbose_name='Color')),
                ('clarity', models.CharField(blank=True, choices=[('0', 'I3'), ('1', 'I2'), ('2', 'I1'), ('3', 'SI2'), ('4', 'SI1'), ('5', 'VS2'), ('6', 'VS1'), ('7', 'VVS2'), ('8', 'VVS1'), ('9', 'IF'), ('10', 'FI')], db_index=True, max_length=150, verbose_name='Clarity')),
                ('origin', models.CharField(blank=True, max_length=150, verbose_name='Origin')),
                ('cut', models.CharField(choices=[('0', 'N/A'), ('1', 'Fair'), ('2', 'Good'), ('3', 'Very Good'), ('4', 'Ideal'), ('5', 'Super Ideal'), ('6', 'Excellent')], max_length=150, verbose_name='Cut')),
                ('polish', models.CharField(blank=True, choices=[('0', 'Good'), ('1', 'Very Good'), ('2', 'Excellent'), ('3', 'N/A')], max_length=150, verbose_name='Polish')),
                ('symmetry', models.CharField(blank=True, choices=[('0', 'N/A'), ('1', 'Good'), ('2', 'Very Good'), ('3', 'Excellent')], max_length=150, verbose_name='Symmetry')),
                ('rap_1ct', models.FloatField(blank=True, verbose_name='Rap. 1ct')),
                ('rap_price', models.FloatField(blank=True, verbose_name='Rap. Price')),
                ('sale_price', models.IntegerField(blank=True, verbose_name='Sale Price')),
                ('disc', models.FloatField(blank=True, verbose_name='Disc')),
                ('weight', models.FloatField(blank=True, db_index=True, verbose_name='Weight')),
                ('length', models.FloatField(blank=True, verbose_name='Length')),
                ('width', models.FloatField(blank=True, verbose_name='Width')),
                ('depth', models.FloatField(blank=True, verbose_name='Depth')),
                ('depth_procent', models.FloatField(blank=True, verbose_name='Depth Procent')),
                ('table_procent', models.FloatField(blank=True, verbose_name='Table')),
                ('lw', models.FloatField(blank=True, verbose_name='L/W: Ratio')),
                ('cert_company', models.CharField(blank=True, choices=[('0', 'IGI'), ('1', 'GIA'), ('2', 'GCAL'), ('3', 'HDR')], max_length=150, verbose_name='Cert Company')),
                ('warehouse', models.CharField(blank=True, max_length=150, verbose_name='Warehouse')),
                ('comments', models.CharField(blank=True, max_length=150, verbose_name='Comments')),
                ('photo', models.ImageField(blank=True, upload_to='diamond_photo/%Y/%m/', verbose_name='Photo')),
                ('video', models.CharField(blank=True, max_length=255, verbose_name='Video')),
                ('gridle_from', models.CharField(blank=True, max_length=150, verbose_name='Gridle From')),
                ('gridle_to', models.CharField(blank=True, max_length=150, verbose_name='Gridle To')),
                ('gridle_type', models.CharField(blank=True, max_length=150, verbose_name='Gridle Type')),
                ('culet', models.CharField(blank=True, max_length=150, verbose_name='Culet')),
                ('fluorescence', models.CharField(blank=True, max_length=150, verbose_name='Fluorescence')),
                ('fluor', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Faint'), ('2', 'Medium'), ('3', 'Strong'), ('4', 'Very Strong')], max_length=150, verbose_name='Fluor')),
                ('on_memo', models.CharField(blank=True, default=0, max_length=150, verbose_name='On memo')),
                ('report_link', models.CharField(blank=True, max_length=255, verbose_name='Report Link')),
                ('color_comment', models.CharField(blank=True, max_length=150, verbose_name='Color Comment')),
                ('shape_ex', models.CharField(blank=True, default='N/A', max_length=150, verbose_name='Shape Ex')),
                ('best_selling', models.BooleanField(blank=True, default=False, verbose_name='Best Selling')),
                ('ref', models.CharField(blank=True, max_length=150, verbose_name='Ref')),
                ('vendor', models.CharField(blank=True, max_length=150, verbose_name='Vendor')),
                ('cert_number', models.CharField(blank=True, max_length=150, verbose_name='Cert. Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Key')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorusers', verbose_name='Vendo ID')),
            ],
            options={
                'verbose_name': 'Diamond',
                'verbose_name_plural': 'Diamonds',
                'ordering': ['sale_price'],
            },
        ),
    ]
