# Generated by Django 4.0.6 on 2022-09-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_diamond_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_diamond_model',
            name='vendor_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorusers', verbose_name='Vendo ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_diamond_model',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='Vendor ID'),
        ),
    ]
