# Generated by Django 4.0.6 on 2022-09-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vedor_diamond_model_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='depth_procent',
            field=models.FloatField(max_length=255, verbose_name='Depth %'),
        ),
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='table_procent',
            field=models.FloatField(max_length=255, verbose_name='Table %'),
        ),
    ]
