# Generated by Django 4.0.6 on 2022-09-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_alter_vedor_diamond_model_depth_procent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='depth',
            field=models.FloatField(verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='depth_procent',
            field=models.FloatField(blank=True, verbose_name='Depth %'),
        ),
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='disc',
            field=models.FloatField(verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='length',
            field=models.FloatField(verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='lw',
            field=models.FloatField(verbose_name='L/W'),
        ),
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='rap_1ct',
            field=models.IntegerField(blank=True, verbose_name='Rap_1ct'),
        ),
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='sale_price',
            field=models.IntegerField(blank=True, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='table_procent',
            field=models.FloatField(blank=True, verbose_name='Table %'),
        ),
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='width',
            field=models.FloatField(verbose_name='Width'),
        ),
    ]
