# Generated by Django 4.0.6 on 2022-09-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_alter_vedor_diamond_model_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='disc',
            field=models.FloatField(blank=True, verbose_name='Discount'),
        ),
    ]
