# Generated by Django 4.0.6 on 2022-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_alter_vedor_diamond_model_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='vedor_diamond_model',
            name='rap_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rap Price'),
            preserve_default=False,
        ),
    ]
