# Generated by Django 4.0.6 on 2022-09-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_vedor_diamond_model_rap_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vedor_diamond_model',
            options={'ordering': ['sale_price'], 'verbose_name': 'Vendor Diamond', 'verbose_name_plural': 'Vendor Diamonds'},
        ),
    ]
