# Generated by Django 4.0.6 on 2022-08-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('0', 'COD'), ('1', 'Invocie'), ('2', 'Cash Memo'), ('3', 'Memo'), ('4', 'Hold')], max_length=1, verbose_name='Order Type')),
                ('order_status', models.CharField(choices=[('0', 'Rejected'), ('1', 'On verification'), ('2', 'Order accepted'), ('3', 'Delivery is in progress'), ('4', 'Delivered'), ('5', 'Completed')], default='1', max_length=1, verbose_name='Order Status')),
                ('order_number', models.CharField(max_length=255, verbose_name='Order Number')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('pay_within', models.IntegerField(blank=True, verbose_name='Pay Within')),
                ('p_ct_offer', models.FloatField(verbose_name='P/ct Offer')),
                ('total_price_offer', models.FloatField(verbose_name='Total Price Offer')),
                ('diamonds_list', models.JSONField(verbose_name='Diamonds List')),
                ('total_diamonds', models.IntegerField(verbose_name='Total Diamonds')),
                ('total_carat', models.FloatField(verbose_name='Total Carat')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartmodal', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['user'],
            },
        ),
    ]
