# Generated by Django 4.0.6 on 2022-08-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_model',
            name='hold_hours',
            field=models.IntegerField(blank=True, default=0, verbose_name='hold_hours'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders_model',
            name='p_ct_offer',
            field=models.FloatField(blank=True, verbose_name='P/ct Offer'),
        ),
        migrations.AlterField(
            model_name='orders_model',
            name='total_price_offer',
            field=models.FloatField(blank=True, verbose_name='Total Price Offer'),
        ),
    ]
