# Generated by Django 4.0.6 on 2022-08-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_model_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_model',
            name='total_price',
            field=models.IntegerField(verbose_name='Total Price'),
        ),
    ]
