# Generated by Django 4.0.6 on 2022-09-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_diamond_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_diamond_model',
            name='order_number',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Order Number'),
            preserve_default=False,
        ),
    ]
