# Generated by Django 4.0.6 on 2022-09-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_diamond_model_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders_diamond_model',
            options={'ordering': ['sale_price'], 'verbose_name': 'Orders Diamond', 'verbose_name_plural': 'Orders Diamonds'},
        ),
        migrations.RenameField(
            model_name='orders_diamond_model',
            old_name='order_id',
            new_name='order',
        ),
    ]
