# Generated by Django 4.0.6 on 2022-09-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orders_diamond_model_rap_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_model',
            name='order_type',
            field=models.CharField(choices=[('0', 'COD'), ('1', 'Invocie'), ('2', 'Cash Memo'), ('3', 'Memo'), ('4', 'Hold')], db_index=True, default='1', max_length=1, verbose_name='Order Type'),
        ),
    ]
