# Generated by Django 4.0.6 on 2022-09-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orders_diamond_model_rap_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_diamond_model',
            name='rap_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rap Price'),
        ),
    ]
