# Generated by Django 4.1.2 on 2022-11-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orders_diamond_model_rap_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_model',
            name='order_number',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Order Number'),
        ),
    ]
