# Generated by Django 4.1.2 on 2022-11-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_orders_model_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_diamond_model',
            name='order_number',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='orders_model',
            name='order_number',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Order Number'),
        ),
    ]
