# Generated by Django 4.0.6 on 2022-08-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharemodel',
            old_name='shareList',
            new_name='share_list',
        ),
        migrations.RemoveField(
            model_name='sharemodel',
            name='shareType',
        ),
        migrations.AddField(
            model_name='sharemodel',
            name='share_type',
            field=models.CharField(choices=[('0', 'Without Prices'), ('1', 'With Prices')], default=1, max_length=1, verbose_name='Share type'),
            preserve_default=False,
        ),
    ]
