# Generated by Django 4.0.6 on 2022-08-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_rename_sharelist_sharemodel_share_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharemodel',
            name='share_key',
            field=models.CharField(default=1, max_length=150, verbose_name='Share Key'),
            preserve_default=False,
        ),
    ]
